### ISSUE TITLE
Migrad fails to converge 

### ISSUE THREAD

**Issue by Jothy** [iminuit/iminuit#119]
Hi all

I am trying to fit some parameters with Migrad, although the results are valid Migrad say it did not converge and the Minos fails to run. The edm is quite large 4352222. The errdef is set to 0.5. Is this a bug. But it works well for other data. I also checked my data and its clean.

Any hints?

Thanks

Jothy

**Comment by cdeil** [comment]
Closing this old issue.
@Jothy – feel free to re-open if you still have this issue.
