### ISSUE TITLE
Bundle Minuit2 instead of SEAL Minuit?

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#124]
Would it be better to bundle Minuit2 instead of SEAL Minuit?
http://seal.web.cern.ch/seal/work-packages/mathlibs/minuit/release/download.html

It seems that since the last release of SEAL Minuit in 2006 quite a few bugs in Minuit have been fixed:
http://seal.web.cern.ch/seal/work-packages/mathlibs/minuit/release/relnotes2.html

@piti118 Do you think the fact that Minuit2 has a bunch of bugs fixed and is actively maintained warrants the work of switching in iminuit? What about the API changes and license?

**Comment by ycopin** [comment]
Is there actually a way to link to an external (supposedly up to date) Minuit2 library, instead of the bundled (out of date) SEAL Minuit?

**Comment by cdeil** [comment]
@ycopin - No, linking against an external Minuit library is currently not supported (see [setup.py](https://github.com/iminuit/iminuit/blob/master/setup.py)).

**Comment by piti118** [comment]
External linking is hard since we need to modify Minuit a little to make it play nicely with Cython. But it's now updated to 2.5. This should be good for years to come. Ref: #145
