### ISSUE TITLE
Wrap FCNGradientBase

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#125]
It looks like one important feature of `Minuit` that is not exposed by `iminuit` is the possibility for the user to compute gradients themselves (see http://root.cern.ch/root/html/ROOT__Minuit2__FCNGradientBase.html).

@piti118 Do you think it would be useful to add this? Any thoughts on how to expose this to the end user?

**Comment by piti118** [comment]
OK noted. This is an important feature. I want to make sure python3 support works first and I'll do this one.

**Comment by iamholger** [comment]
Dear developers, 

in our project (professor.hepforge.org) we switched from pyminuit to iminuit entirely and are very happy with it. The above mentioned feature would benefit our project as we can often construct the gradient of the function we want to minimise. Cpu time of the minimisation currently limits the application to ~ 10 dimensional parameter spaces so it would be cool to go beyond that. 
Do you have an estimate on whether that MINUIT functionality will be part of iminuit anytime soon?

Thanks,
Holger

**Comment by cdeil** [comment]
This was implemented by @chrisburr in #182.
Closing this issue.

Everyone: please try it out on your applications and give feedback.

**Comment by iamholger** [comment]
Thanks a lot for providing this functionality. The usage is nice and simple. I did a few consistency checks and found the minimisation results with numerical and analytical gradients to be consistent. 
I will do more testing soon. 

We have some output in our minimisation stage that looks like that now:
 ******************************************************************
* Using iminuit, please visit https://github.com/iminuit/iminuit *
*******************************************************************

Let me know if you want something else or more verbose.

Thanks a lot!
