### ISSUE TITLE
Provide iminuit via conda /  binstar

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#127]
[conda](http://conda.pydata.org/) is very popular ... it would be nice if we could make it easy to install `iminuit` via `conda install iminuit` ... especially for Windows users (see #115).

I think the way to do it is to write a recipe and [binstar](https://binstar.org/) can be used to build and distribute binary packages, but I've never done this.
Does anyone know / has time to do this?

There is https://binstar.org/pypi/iminuit, but I think that's just a copy of the source tarball from PyPI, i.e. not useful.

**Comment by fabianrost84** [comment]
I did build one with conda but only for linux-64. Available like this:
<code>conda install -c https://conda.binstar.org/fabianrost iminuit</code>

I used the git repository. Unfortunately, there are no version tags, so I manually set the version to 0.0.150511 (todays date).

**Comment by cdeil** [comment]
@asmeurer – A new release of `iminuit` that supports Python 3 is available now:
https://pypi.python.org/pypi/iminuit/1.2

Any chance that this gets built and distributed via a Continuum or community-maintained conda channel?

**Comment by asmeurer** [comment]
@ilanschnell @groutr

**Comment by cdeil** [comment]
@mwcraig produced conda packages for iminuit, they are available via the astropy channel:
https://anaconda.org/astropy/iminuit

Before I put that info in the iminuit install docs, one last try...

@ilanschnell @groutr - Is it possible to get `iminuit` in Anaconda or some other channel where Continuum builds the packages when new versions come out? MINUIT is very much liked by scientists and it's a very robust package for model fitting. But maybe it's too niche and at least for now distributing it via the astropy channel is more appropriate?

**Comment by ilanschnell** [comment]
Thanks for reaching out.  I see that iminuit only has had one release so far: https://github.com/iminuit/iminuit/tags  We can only add released (tagged) versions of iminuit to the official Anaconda repository.
 What type of release frequency can we expect?  Perhaps the astropy channel is more appropriate, at least for now.  This way you have complete control over how you push conda packages (without having to bug us).

**Comment by cdeil** [comment]
@ilanschnell - There's two stable releases of iminuit on PyPI:

* https://pypi.python.org/pypi/iminuit/1.1.1 from 2014-01-28
* https://pypi.python.org/pypi/iminuit/1.2 from 2015-11-10

MINUIT is 30 years old (the C++ version we wrap is 10 years old) and iminuit is a few years old.
The development activity is low, I think for the coming years maybe ~ yearly releases.

**Comment by ilanschnell** [comment]
I like slow release cycles!  I'll look into it, or at least put it on the agenda.

**Comment by cdeil** [comment]
For now I'm advertising the astropy conda channel for iminuit users:
http://iminuit.readthedocs.org/en/latest/installation.html#conda

Closing this issue now.

@ilanschnell - Please let us know if iminuit makes it into the official Anaconda repo some day and we'll update the docs.

**Comment by cdeil** [comment]
I see that `iminuit` is now available in a few channels:
https://anaconda.org/search?q=iminuit

@ilanschnell - is this the official Anaconda channel, that users have per default?
https://anaconda.org/anaconda/iminuit
If yes, that would be awesome, and I'd point out that in our docs.
Also, if yes, could you please update iminuit to 1.2 there? Or can I make a pull request to do that somewhere myself?

**Comment by asmeurer** [comment]
I would suggest adding it to [conda-forge](https://conda-forge.github.io/).

**Comment by mwcraig** [comment]
Looks like 1.1.1 is on defaults. If you add it to conda-forge it will continue to be copied over to the astropy channel also.

**Comment by cdeil** [comment]
Just in case anyone finds this old thread: `iminuit` is being added to `conda-forge` right now: https://github.com/conda-forge/staged-recipes/pull/3479 which seems to be a good and long-term solution for conda packages.

@mwcraig - Thank you!
