### ISSUE TITLE
Google Page Requests

### ISSUE THREAD

**Issue by jdermigny** [iminuit/iminuit#136]
hello,
the iminuit documentation has been difficult to access from google, all the old http://iminuit.github.io/ pages are still found but give you 404 error. Just thought I should point this out.
Jack

**Comment by cdeil** [comment]
For me the first few Google search results for `iminuit` look OK now (see screenshot)

@jdermigny – Can you check again?

![screen shot 2015-04-24 at 17 35 18](https://cloud.githubusercontent.com/assets/852409/7322466/6d4cb22e-eaa8-11e4-862a-0a729e69b0c0.png)

**Comment by jdermigny** [comment]
looks great from my end.
jack
On Apr 24, 2015, at 11:36 AM, Christoph Deil <notifications@github.com<mailto:notifications@github.com>> wrote:


For me the first few Google search results for iminuit look OK now (see screenshot)

@jdermigny<https://github.com/jdermigny> – Can you check again?

[screen shot 2015-04-24 at 17 35 18]<https://cloud.githubusercontent.com/assets/852409/7322466/6d4cb22e-eaa8-11e4-862a-0a729e69b0c0.png>
