### ISSUE TITLE
Typo in RuntimeError

### ISSUE THREAD

**Issue by iRaffnix** [iminuit/iminuit#138]
Found misspelled RuntimeError class in _libiminuit.pyx.
You wrote RunTimeError instade of RuntimeError.
 
I have a patch but I dont know where to upload?!

**Comment by cdeil** [comment]
@iRaffnix – Thanks for reporting this! Can you make a [pull request on Github](https://help.github.com/articles/using-pull-requests/)?

**Comment by iRaffnix** [comment]
I have already done this. Have a nice day...
Am 20.04.2015 22:04 schrieb "Christoph Deil" <notifications@github.com>:

**Comment by cdeil** [comment]
Fixed by @iRaffnix in PR #139.
