### ISSUE TITLE
Migrad fails to converge and do not run MINOS

### ISSUE THREAD

**Issue by astroyama** [iminuit/iminuit#142]
Hello all,
Now I attempt maximum likelihood fitting to many image data sets by using iminuit .
When I evaluated Minuit() and migrad(), I got Valid=False.
So, I cannot evaluate MINOS().
The reason why I got Valid=False is that edm value is not below 5e-06.
Do you have any advise to get Valid=True?
In some image data sets, I complete the image fitting excluded  Valid=False.
```
Elapsed Time: 592 sec Call: 12993/10000 (0.0456 sec/call).
Est. time to maxcall: -136.37 sec.
FCN=-4.464549e+06 FROM MIGRAD  STATUS=VALID   1425 CALLS
EDM=6.956401e-04 ERROR MATRIX ACCURATE POSDEF
NO.       NAME         VALUE         ERROR  FIXED
  0        N_1  1.780925e-04  7.123156e-06       
  1        N_2  1.611644e-04  6.493789e-06       
  2        N_3  1.296069e-03  1.373725e-05       
  3        N_4  -1.004128e-04  6.791097e-06       
  4        N_5  -3.671819e-02  4.654784e-05       
  5        N_6  1.927801e-04  7.005470e-06       
  6        N_7  -2.606878e-04  8.430227e-06       
  7        N_8  -1.449193e-04  7.780656e-06       
  8        N_9  2.744544e-03  1.758545e-05       
  9       N_10  1.527588e-04  5.934882e-06       
 10       N_11  1.068726e-04  7.324632e-06       
 11       N_12  5.599161e-04  8.135475e-06       
 12       N_13  -4.124206e-05  6.877125e-06       
 13       N_14  -1.216139e-10  1.402877e-07       
 14        bkg  3.311752e-05  1.308920e-07       
##############################################################################
--------------------------------------
**********************************************************************
---------------------------------------------------------------------------------------
fval = -4464548.903636946 | total call = 13001 | ncalls = 1425
edm = 0.0006956400528321152 (Goal: 5e-06) | up = 0.5
---------------------------------------------------------------------------------------
|          Valid |    Valid Param | Accurate Covar |         Posdef |    Made Posdef |
---------------------------------------------------------------------------------------
|          False |           True |           True |           True |          False |
---------------------------------------------------------------------------------------
|     Hesse Fail |        Has Cov |      Above EDM |                |  Reach calllim |
---------------------------------------------------------------------------------------
|          False |           True |          False |             '' |           True |
---------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------
|      | Name  |  Value   | Para Err |   Err-   |   Err+   |  Limit-  |  Limit+  |          |
----------------------------------------------------------------------------------------------
|    0 |   N_1 =  0.0001781 |  7.123E-06 |          |          |          |          |          |
|    1 |   N_2 =  0.0001612 |  6.494E-06 |          |          |          |          |          |
|    2 |   N_3 =  0.001296 |  1.374E-05 |          |          |          |          |          |
|    3 |   N_4 = -0.0001004 |  6.791E-06 |          |          |          |          |          |
|    4 |   N_5 = -0.03672 |  4.655E-05 |          |          |          |          |          |
|    5 |   N_6 =  0.0001928 |  7.005E-06 |          |          |          |          |          |
|    6 |   N_7 = -0.0002607 |  8.43E-06 |          |          |          |          |          |
|    7 |   N_8 = -0.0001449 |  7.781E-06 |          |          |          |          |          |
|    8 |   N_9 =  0.002745 |  1.759E-05 |          |          |          |          |          |
|    9 |  N_10 =  0.0001528 |  5.935E-06 |          |          |          |          |          |
|   10 |  N_11 =  0.0001069 |  7.325E-06 |          |          |          |          |          |
|   11 |  N_12 =  0.0005599 |  8.135E-06 |          |          |          |          |          |
|   12 |  N_13 = -4.124E-05 |  6.877E-06 |          |          |          |          |          |
|   13 |  N_14 = -1.216E-10 |  1.403E-07 |          |          |          |          |          |
|   14 |   bkg =  3.312E-05 |  1.309E-07 |          |          |          |          |          |
----------------------------------------------------------------------------------------------

**********************************************************************
**************************************************
*                     MINOS                      *
**************************************************

Traceback (most recent call last):
  File "fit_model.py", line 83, in <module>
    all=f.minos()
  File "_libiminuit.pyx", line 414, in iminuit._libiminuit.Minuit.minos (iminuit/_libiminuit.cpp:5796)
RuntimeError: Function mimimum is not valid. Make sure migrad converge first  
```

**Comment by astroyama** [comment]
This is my stdout.

Elapsed Time: 592 sec Call: 12993/10000 (0.0456 sec/call).
Est. time to maxcall: -136.37 sec.
FCN=-4.464549e+06 FROM MIGRAD  STATUS=VALID   1425 CALLS
EDM=6.956401e-04 ERROR MATRIX ACCURATE POSDEF
NO.       NAME         VALUE         ERROR  FIXED
  0        N_1  1.780925e-04  7.123156e-06       
  1        N_2  1.611644e-04  6.493789e-06       
  2        N_3  1.296069e-03  1.373725e-05       
  3        N_4  -1.004128e-04  6.791097e-06       
  4        N_5  -3.671819e-02  4.654784e-05       
  5        N_6  1.927801e-04  7.005470e-06       
  6        N_7  -2.606878e-04  8.430227e-06       
  7        N_8  -1.449193e-04  7.780656e-06       
  8        N_9  2.744544e-03  1.758545e-05       
  9       N_10  1.527588e-04  5.934882e-06       
 10       N_11  1.068726e-04  7.324632e-06       
 11       N_12  5.599161e-04  8.135475e-06       
 12       N_13  -4.124206e-05  6.877125e-06       
 13       N_14  -1.216139e-10  1.402877e-07       
 14        bkg  3.311752e-05  1.308920e-07       
--------------------------------------
**********************************************************************
---------------------------------------------------------------------------------------
fval = -4464548.903636946 | total call = 13001 | ncalls = 1425
edm = 0.0006956400528321152 (Goal: 5e-06) | up = 0.5
---------------------------------------------------------------------------------------
|          Valid |    Valid Param | Accurate Covar |         Posdef |    Made Posdef |
---------------------------------------------------------------------------------------
|          False |           True |           True |           True |          False |
---------------------------------------------------------------------------------------
|     Hesse Fail |        Has Cov |      Above EDM |                |  Reach calllim |
---------------------------------------------------------------------------------------
|          False |           True |          False |             '' |           True |
---------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------
|      | Name  |  Value   | Para Err |   Err-   |   Err+   |  Limit-  |  Limit+  |          |
----------------------------------------------------------------------------------------------
|    0 |   N_1 =  0.0001781 |  7.123E-06 |          |          |          |          |          |
|    1 |   N_2 =  0.0001612 |  6.494E-06 |          |          |          |          |          |
|    2 |   N_3 =  0.001296 |  1.374E-05 |          |          |          |          |          |
|    3 |   N_4 = -0.0001004 |  6.791E-06 |          |          |          |          |          |
|    4 |   N_5 = -0.03672 |  4.655E-05 |          |          |          |          |          |
|    5 |   N_6 =  0.0001928 |  7.005E-06 |          |          |          |          |          |
|    6 |   N_7 = -0.0002607 |  8.43E-06 |          |          |          |          |          |
|    7 |   N_8 = -0.0001449 |  7.781E-06 |          |          |          |          |          |
|    8 |   N_9 =  0.002745 |  1.759E-05 |          |          |          |          |          |
|    9 |  N_10 =  0.0001528 |  5.935E-06 |          |          |          |          |          |
|   10 |  N_11 =  0.0001069 |  7.325E-06 |          |          |          |          |          |
|   11 |  N_12 =  0.0005599 |  8.135E-06 |          |          |          |          |          |
|   12 |  N_13 = -4.124E-05 |  6.877E-06 |          |          |          |          |          |
|   13 |  N_14 = -1.216E-10 |  1.403E-07 |          |          |          |          |          |
|   14 |   bkg =  3.312E-05 |  1.309E-07 |          |          |          |          |          |
----------------------------------------------------------------------------------------------

**********************************************************************
**************************************************
*                     MINOS                      *
**************************************************

Traceback (most recent call last):
  File "fit_model.py", line 83, in <module>
    all=f.minos()
  File "_libiminuit.pyx", line 414, in iminuit._libiminuit.Minuit.minos (iminuit/_libiminuit.cpp:5796)
RuntimeError: Function mimimum is not valid. Make sure migrad converge first

**Comment by cdeil** [comment]
I think your output shows `STATUS=VALID` printed by C++ Minuit and then `Valid=False` printed by the iminuit wrapper? This is a bit weird and I don't know exactly how these two flags are computed. @piti118 Shouldn't they be the same?

Just some thoughts ... I'm not sure they are helpful:
* Increase `print_level` to get more info printed to the console (see [here](http://iminuit.readthedocs.org/en/latest/api.html?highlight=verbose#iminuit.Minuit)?
* Call `hesse` before calling `minos`?
* Change `precision` when calling migrad (see [here](http://iminuit.readthedocs.org/en/latest/api.html?highlight=verbose#iminuit.Minuit.migrad))? (I don't know what the default is and if changing this helps.)

**Comment by astroyama** [comment]
Thank you for your comments.
>>>I think your output shows STATUS=VALID printed by C++ Minuit and then Valid=False printed by the >>>iminuit wrapper?
If it is true, it is very strange.  I may be panicked.

Attempting your helps, I got the same output Valid=False and cannot evaluate MINOS().

**Comment by astroyama** [comment]
Sorry, I want to write one more comment.

>>>Change precision when calling migrad (see here)? (I don't know what the default is and if changing this helps.)

When I evaluated `f.migrad(precision=0.001)`,
I got the error :
```
TypeError: migrad() got an unexpected keyword argument 'precision'
```

**Comment by cdeil** [comment]
@astroyama – Do you still have this problem? Or should we close this old issue?

Concerning your last comment, [Minuit.migrad](http://iminuit.readthedocs.org/en/latest/api.html#iminuit.Minuit.migrad) should accept a `precision` keyword argument. I tried this simple example with the latest version from master and it works fine:
```python
from iminuit import Minuit
def f(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2
m = Minuit(f)
m.migrad(precision=0.1)
```

If you still can reproduce this issue, could you please update to the latest development version and try again? Or alternatively, extract a test case that we can try?

**Comment by cdeil** [comment]
Closing this issue because of lack of feedback.

@astroyama - If you still have have this issue, please comment here and we'll re-open!

Also --  I've just now set up a mailing list to encourage more questions / discussions by users on iminuit ... please sign up here:
https://groups.google.com/forum/#!forum/iminuit

**Comment by JaySandesara** [comment]
Hello,

I am facing the same issue again with using precision (or any other argument really) in migrad. I recreated the exact example @cdeil mentioned:

`from iminuit import Minuit
def f(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2
m = Minuit(f)
m.migrad(precision=0.1)`

And I end up getting the error:

`TypeError                                 Traceback (most recent call last)
<ipython-input-32-69b3633f7d19> in <module>
      4 
      5 m = Minuit(f, (0.0,0.0,0.0))
----> 6 m.migrad(precision=0.1)

TypeError: migrad() got an unexpected keyword argument 'precision'`

Can you please help? I am using iminuit v2.16.0. Note that migrad doesn't even take ncalls argument.
