### ISSUE TITLE
Docstring for draw_mnprofile is mis-formatted

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#151]
I noticed that currently the docstring for [iminuit.Minuit.draw_mnprofile](http://iminuit.readthedocs.org/en/latest/api.html#iminuit.Minuit.draw_mnprofile) is mis-formatted, namely the `bound` and `subtract_min` arguments are formatted differently from the others:

<img width="699" alt="screen shot 2015-08-01 at 17 36 35" src="https://cloud.githubusercontent.com/assets/852409/9022396/00e66462-3874-11e5-8ceb-520549769e57.png">

Any idea how to fix this?

More general question:
@piti118 – Pretty much scientific Python packages use the numpy docstring standard. How do you feel about using this for `iminuit`? If I make a PR for this, would you accept it or do you strongly prefer the current docstring format?

**Comment by piti118** [comment]
I'd follow whatever style rootpy is using (whatever it is). Since a lot of our users are rootpy users, they will feel right at home.

**Comment by cdeil** [comment]
@piti118 – OK, I've split off the docstring formatting to #155 to keep this issue focused on this error mentioned in the description above.

**Comment by cdeil** [comment]
Closing this issue.
It was fixed by @lgeiger in #168 
Looks good now: http://iminuit.readthedocs.org/en/latest/api.html#iminuit.Minuit.draw_mnprofile

![screen shot 2015-09-28 at 19 39 37](https://cloud.githubusercontent.com/assets/852409/10143447/b74234da-6618-11e5-864b-3c9c621982e3.png)
