### ISSUE TITLE
Clean up Minuit.merrors?

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#153]
The [Minuit.merrors](http://iminuit.readthedocs.org/en/latest/api.html#iminuit.Minuit.merrors) interface and a few other things are non-ideal to maintain compatibility with the PyMinuit API.

I'm +1 to clean this up and make an `iminuit 2.0` release.

@piti118 What do you think? Is there a ton of "legacy pyminuit scripts" that you want to support via iminuit, i.e. breaking backward compatibility is not an option?

**Comment by piti118** [comment]
I'd leave it for now. If we need to do a major haul on the _libminuit, the compatibility would not be of our concern anymore.

**Comment by cdeil** [comment]
This was 3 years ago. By now I think we should just keep `iminuit` as-is. (working, maybe not pretty in some places)
