### ISSUE TITLE
iminuit 1.2 release

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#154]
Now that `iminuit` is Python 3 compatible, it would be great to have a release.

There's a few issues on the 1.2 milestone, but I think these can quickly be addressed, e.g. I have some time tomorrow:
https://github.com/iminuit/iminuit/milestones/1.2

@piti118 – Do you agree it's time to cut a release? Do you have time to do it soon?

We can use this GH issue to discuss release-related issues and TODOs and checks.

**Comment by cdeil** [comment]
PS: my motivation is that I want to use `iminuit` in a few places for [gammapy](https://github.com/gammapy/gammapy), but I need Python 3 and a release and ideally conda packages so that I can quickly install it on travis-ci builds.

**Comment by piti118** [comment]
If there is no major functionality issue with the python3 fix I made, go ahead make 1.2 release. Cosmetic issue is tolerable But, I'll leave that job to you. :)

**Comment by cdeil** [comment]
I've been using iminuit with Python 3 for a day now and haven't seen any issues, I think it's a good idea to cut a release and get some more wider testing.
OK, I'll try to resolve the remaining issues / cosmetic changes tomorrow and cut a release tomorrow or next week.

**Comment by cdeil** [comment]
Based on https://github.com/iminuit/iminuit/issues/86#issuecomment-126936313 I'm changing the plan. We'll call the next release 2.0, not 1.2.
This will allow us to not be 100% backwards compatible, e.g. in #86.
Just to be clear, I don't plan to make huge changes, just the small ones mentioned.

Renaming this issue and the milestone now.

**Comment by piti118** [comment]
Sure 2.0 sounds good.

**Comment by ycopin** [comment]
Now that head iminuit made a big jump forward by supporting python-3 and including Minuit2 library, what about releasing a 2.0 version? Are all the milestone:2.0 issues still valid, or which ones are critical?

**Comment by cdeil** [comment]
@ycopin – I don't think any of the issues labeled with the 2.0 milestone are critical.

Here's a first release candidate on testpypi based on the current git master version 5ea4635f52b7e4b2524f7d80d103716ef8de1b16 :
https://testpypi.python.org/pypi/iminuit/2.0rc0

Everyone please try to install it and run tests an machines you have access to and report any issues (or success) you find.

If there's no issues, I'll cut the 2.0 release next week.

I don't know if I'll have time to do some cleanup, so if anyone has time to improve docstrings / docs / tackle any of the open issues within the next few days, that would be great!

**Comment by cdeil** [comment]
Actually the change in #86 isn't made yet, so `iminuit` should be backwards compatible.
So let's call this upcoming release 1.2 after all, OK?
(I'll try to track down the issue with #170 tomorrow and then make the release ... so if anyone wanted to do some more testing / changes, please do it today or comment here if you plan to do it later this week.)

**Comment by cdeil** [comment]
Here's the release:
https://pypi.python.org/pypi/iminuit/1.2

Please test and report any issues!

@piti118 – There's no mailing lists where this could be announced / advertised, right?

**Comment by piti118** [comment]
May be we should set up one of those google group.

**Comment by cdeil** [comment]
I just now set up this Google group:
https://groups.google.com/forum/#!forum/iminuit

I'll add a link to the docs ...
