### ISSUE TITLE
'print_level=2' doesn't work in python 3

### ISSUE THREAD

**Issue by mattngc** [iminuit/iminuit#165]
Levels 0 and 1 both work as expected, but not at level 2.

**Comment by cdeil** [comment]
@mattngc – Print level for which method doesn't work as expected?

If you could produce a minimal code example that shows the issue, that would help a lot to pin this down and fix it quickly (and add a regression test to make sure it stays fixed). You're saying this gives the output you expect on Python 2 but not Python 3?

**Comment by piti118** [comment]
This is because when we move from Minuit1.xx to Minuit2.xx I probably forgot to add some print function.

Print level 2 comes from Modified version of Minuit.

**Comment by HDembinski** [comment]
@mattngc Hi, if you are still reading this, could you try the latest master version to whether your problem was solved?

**Comment by mattngc** [comment]
Hi @HDembinski , I haven't used this library for a while. So not easy for me to test straight away. But thanks for looking at it.

**Comment by cdeil** [comment]
I'm closing this issue now.

If anyone still finds an issue in the future related to this, please re-open or file a new one!
