### ISSUE TITLE
Errors for a particular parameter set all equal 1

### ISSUE THREAD

**Issue by jimcost** [iminuit/iminuit#172]
I am fitting a 31 parameter equation, containing 4 parameter sets and 3 individual parameters.  The equation looks like - 

![image](https://cloud.githubusercontent.com/assets/6710629/10959627/f90dc23a-8337-11e5-8bbe-e6a4976f5f64.png)

For one of my parameter sets (e_k) all of the errors extracted equal 1.  Curiously, this is not the case for any other parameter.  My 'errordef' equals 2, and I am using a chi^2 objective function (produced by the probit module).

My question - is there code within iminuit that, under certain circumstances, forces errors to equal 1?

**Comment by piti118** [comment]
It could be the case of default error value(I don't think so) but check your fit status.

**Comment by jimcost** [comment]
Is the fit status and 'migrad_ok()' variable the same?  I use a 'while' loop is ensure the migrad is "valid" (see below)

﻿	while m.migrad_ok() == False:
			m.migrad(ncall = 10e4)

**Comment by jimcost** [comment]
I found the issue, and it was (my) human error.  Using indices with a dictionary.  Plus I am only fitting half of the parameters in each of the sets (troubleshooting purposes, fixing the other parameters at zero).

Thanks for the help Piti!
