### ISSUE TITLE
Analytical derivatives?

### ISSUE THREAD

**Issue by giacomov** [iminuit/iminuit#175]
Is there a way to specify the analytical derivatives of the function to minimize?

For simple functions this speed up a lot the fitting, and it is a feature implemented in Minuit2.

**Comment by cdeil** [comment]
This is the same feature request as #125.
As far as I know, this Minuit2 functionality hasn't been exposed in iminuit and no-one's working on it at the moment.

**Comment by cdeil** [comment]
This was implemented by @chrisburr in #182.
Closing this issue.

Everyone: please try it out on your applications and give feedback.
