### ISSUE TITLE
TypeError: only length-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by deisi** [iminuit/iminuit#176]
I have the following error:

```
%pylab inline
from pylab import *
from iminuit import Minuit, describe, Struct

x = arange(10)
noise = np.random.normal(size=10)
y = 3*x + 1 + noise

def f(m,b):
     return y - m*x+b 

m=Minuit(f, m=2, error_m=0.2, limit_m=(-10.,10.), b=0., print_level=1)
m.print_param()

m.migrad();
```

and I get

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-8bd12ea0f76c> in <module>()
      14 
      15 #Minimize
---> 16 m.migrad();
     17 #notice also in your prompt it prints out progress
 18 

iminuit\_libiminuit.pyx in iminuit._libiminuit.Minuit.migrad (iminuit/_libiminuit.cpp:5293)()

TypeError: only length-1 arrays can be converted to Python scalars
```

Am I using it wrongly or can it be a problem of python 3.4 (Anaconda3 on windows) and installed iminuit via [Christoph Gohlke's](Christoph Gohlke) package?

**Comment by cdeil** [comment]
@deisi - You have to git a cost function `f` to `Minuit` that returns a scalar (i.e. the summed likelihood or  chi^2). You are passing a function that returns an array.

Example:  https://github.com/gammapy/PyGamma15/blob/gh-pages/tutorials/analysis-stats/TutorialSolutions.ipynb

@deisi - Does this help? Can you get your fit to work?

**Comment by cdeil** [comment]
I've just now set up a mailing list to encourage more questions / discussions by users on iminuit ... please sign up here:
https://groups.google.com/forum/#!forum/iminuit

**Comment by deisi** [comment]
Ah okay, I see of course, I cant check it right now, but I will ASAP and then I tell you, but I think. This is it. Thanks.

**Comment by cdeil** [comment]
I'm closing this old issue now; I don't think there's an action item here for us.

@deisi - The tutorials are much improved now: http://iminuit.readthedocs.io/en/latest/tutorials.html
