### ISSUE TITLE
Issue in compilation

### ISSUE THREAD

**Issue by rodiram** [iminuit/iminuit#183]
Thank you for including the gradient option !
I have an issue when installing the new version (downloaded yesterday) :
Linux  3.10.0-123.9.2.el7.x86_64 #1 SMP Tue Oct 28 13:59:15 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Aug 21 2014, 18:22:21) 

[iminuit-master]$python setup.py install --prefix=/home/anaconda/
Compiling iminuit/_libiminuit.pyx because it changed.
Cythonizing iminuit/_libiminuit.pyx
## Error compiling Cython file:

...
    #int raise_py_err()#this is very important we need custom error handler
    FunctionMinimum*call_mnapplication_wrapper( \
            MnApplication app, unsigned int i, double tol) except +
    cdef cppclass PythonFCN(FCNBase, PythonFCNBase):
        PythonFCN( \
                object fcn, double up_parm, vector[string] pname, bint thrownan)
##                ^

iminuit/_libiminuit.pyx:57:16: no matching function for call to PythonFCNBase::PythonFCNBase()
## Error compiling Cython file:

...

cdef extern from "PythonGradientFCN.h":
    #int raise_py_err()#this is very important we need custom error handler
    cdef cppclass PythonGradientFCN(FCNBase, PythonFCNBase):
        PythonGradientFCN( \
                object fcn, object grad_fcn, double up_parm, vector[string] pname, bint thrownan)
##                ^

iminuit/_libiminuit.pyx:68:16: no matching function for call to PythonFCNBase::PythonFCNBase()
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    extensions = cythonize(extensions)
  File "/home/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 825, in cythonize
    cythonize_one(*args[1:])
  File "/home/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 944, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: iminuit/_libiminuit.pyx

**Comment by rodiram** [comment]
I have added the line 
cdef extern from "PythonFCNBase.h":
    cdef cppclass PythonFCNBase:
        PythonFCNBase()   ## added here

in the file _libiminuit.pyx 
It seems to be working
( gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) )

**Comment by HDembinski** [comment]
PythonFCNBase is gone now, so this issue can be closed.
