### ISSUE TITLE
grad_fcn with parameters given in an array 

### ISSUE THREAD

**Issue by rodiram** [iminuit/iminuit#185]
Adding the gradient option in iminuit.Minuit speeds-up a lot the minimization when numerous variables are used. Thank you for this recent improvement.
From what I've understood, the variable values at which the gradient will be calculated must be given explicitly in the gradient function: 
def func4_grad(x, y, z):
...
this is not possible when fitting lot's of variables (cases for which the gradient input is needed).
Is there a way to use an array as argument to the gradient function ? I tried but it did not work, I could not find the corresponding line code in the sources files. Something like:
def func4_grad(double[::1] my_variables):
...
Thanks !

**Comment by rodiram** [comment]
I see that in PythonGradientFCN.h the grad function is called with a vector in Gradient:
Gradient(const std::vector<double>& x)
PyObject* tuple = vector2tuple(x);
PyObject* result = PyObject_Call(gradfcn,tuple,NULL);
..
But I can not find the link between this function and the grad_fcn function of _libiminuit.pyx which is provided by the user.
Can someone points the lines where it is done ?

**Comment by rodiram** [comment]
Is iminuit still maintained ? If not it would be useful to mention it somewhere since it is an important parameter when one chooses an option or another. Thank you anyway for this work.

**Comment by cdeil** [comment]
@HDembinski - Assigning to you and the v1.3 milestone.

Does this require further code changes? Or "just" docs improvements to explain how to use functions with gradients or the new array interface that you added recently?

**Comment by HDembinski** [comment]
This feature works now with the master, no further code changes needed. I just added an explicit test for this case. All this will be in the docs when we describe the new feature of using Minuit with array-based functions.
