### ISSUE TITLE
[Add] 2d scan similar to 1D scan

### ISSUE THREAD

**Issue by londumas** [iminuit/iminuit#187]
Thank you for the super work ! iminuit is very usefull.

Is there a way or a chance to add a 2D scan method similar to the 1D one ?
Because mncontour_grid doesn't allow to set the range of the parameters, when mnprofile does allow it.

I have coded a 2D scan in python with minuit but setting the following in each iteration is very uneficient.

```
for i in range(par_nb_bin1):

            for j in range(par_nb_bin2):

                mig.fitarg[par_name1] = grid1[i]

                mig.fitarg[par_name2] = grid2[j]

                mig = iminuit.Minuit(chi2,**mig.fitarg)

                mig.migrad()

                result[i][j] = mig.get_fmin()['fval']
```

**Comment by HDembinski** [comment]
The method `contour` does a 2D scan.
