### ISSUE TITLE
[bug] minos minos sigma=2 gives one sigma error

### ISSUE THREAD

**Issue by londumas** [iminuit/iminuit#188]
When fixing sigma=2. to minos, the given errors are the same as not fixing it. So I bet they give the one sigma error.

**Comment by cdeil** [comment]
@londumas - Thanks for the bug report!

For reference, the API docs for `Minuit.minos` are [here](http://iminuit.readthedocs.io/en/latest/api.html#iminuit.Minuit.minos) and the tests are in [iminuit/tests/test_iminuit.py](https://github.com/iminuit/iminuit/blob/master/iminuit/tests/test_iminuit.py).

Looks like there is no test that calls `minos` passing a `sigma`.
There's only one test passing `sigma`  to `mncontour`: `test_mncontour_sigma`.

@londumas - Can you contribute a test that shows the issue, i.e. runs a minimal example and has an assert statement at the end on what you expect, that currently fails.
That would be the first step, then the next one is to look at the implementation and fix it.

I don't have time, sorry.
Help welcome!

**Comment by londumas** [comment]
ok, I am writing it. interestingly, it works in 1.1.1

**Comment by cdeil** [comment]
@londumas - Thank you!

**Comment by londumas** [comment]
Here is a working example. Could you have a look ?

import numpy
import iminuit

nb_sigma_for_minos = 2.
loc   = 0.
scale = 1.
size  = 100000
step  = 0.1*scale
edge  = 4.*scale

numpy.random.seed(42)
rand = numpy.random.normal(loc=loc,scale=scale,size=size)
rand = rand[ numpy.logical_and(rand>loc-edge,rand<loc+edge)]
y,bin_edges = numpy.histogram(rand,bins=numpy.arange(loc-edge,loc+edge,step))
x = (bin_edges[:-1] + bin_edges[1:])/2.
yer = numpy.sqrt(y)

def chi2(mu,sigma,A):
	
	g = A*numpy.exp(-(x-mu)**2/(2.*sigma**2))/(numpy.sqrt(2.*numpy.pi)*sigma)
	
	return numpy.sum(numpy.power((y-g)/yer,2.))
m = iminuit.Minuit(chi2,mu=loc,sigma=scale,A=size*step,error_mu=1.,error_sigma=1.,error_A=1.,errordef=0.01,print_level=0)
m.migrad()

m.minos(var='mu',sigma=nb_sigma_for_minos)
mu_error_measured = m.get_merrors()['mu']['upper']
mu_error_expected = nb_sigma_for_minos*scale/numpy.sqrt(size)*step
print '  for 2 sigma, error(mu)_expected = ', mu_error_expected
print '  for 2 sigma, error(mu)_measured = ', mu_error_measured

**Comment by londumas** [comment]
[test_error_minos.txt](https://github.com/iminuit/iminuit/files/356625/test_error_minos.txt)

**Comment by londumas** [comment]
I have a way simplier example here:

import iminuit

def f(x):
	return x**2

m= iminuit.Minuit(f)
m.migrad()
 # ==> error = +/- 1
m.minos()
  # ==> error = +/- 2
m.minos(sigma=2)
#===> error = +/- 3
m.minos(sigma=3

**Comment by londumas** [comment]
What can I do to have this issue fixed ?

**Comment by londumas** [comment]
The bug might be in iminuit/_libiminuit.pyx,

self.pyfcn.set_up(oldup * sigma * sigma) at line 569

could you have a look, it could be cool to fix that.

**Comment by londumas** [comment]
something might have happen here:

https://github.com/iminuit/iminuit/commit/cf718b74c24ed79e96b186d4cec556b2b1ceac8d

because there is no problem iniminuit==1.2 

@chrisburr could you look what changed you have made that broke the minos sigma errors ?

**Comment by cdeil** [comment]
@londumas - This should be fixe now, by @HDembinski in #210.

I'm closing this issue now.

Please try with the latest iminuit master, and if there still is a problem, please re-open or file a new issue.

**Comment by londumas** [comment]
@cdeil, it is fixed.
