### ISSUE TITLE
ImportError on anaconda

### ISSUE THREAD

**Issue by jaromrax** [iminuit/iminuit#194]
I have anaconda3 python 3.5, recently installed. I tried both ways to install iminuit - pip and git, both give me
```
./iminu.py     
Traceback (most recent call last):
  File "./iminu.py", line 2, in <module>
    from iminuit import Minuit
  File "/home/ojr/anaconda3/lib/python3.5/site-packages/iminuit/__init__.py", line 27, in <module>
    from iminuit._libiminuit import *
ImportError: /home/ojr/anaconda3/lib/python3.5/site-packages/iminuit/_libiminuit.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
```
Any idea?

**Comment by cdeil** [comment]
@jaromrax - I don't know what went wrong from the error you posted. I would need to see the full output to see which compiler was used to compile Minuit and iminuit during the install.

Could you please either post that, e.g. in a gist (https://gist.github.com/)?

Or, if you don't need the development version of iminuit, try to install an iminuit conda package (see https://anaconda.org/search?q=iminuit).
This should work:
```
pip uninstall iminuit # remove the broken version you have now
conda install -c astropy iminuit=1.2 # install latest stable iminuit release as a conda package
```
Conda packages are binary packages, i.e. no compiler is needed during conda install.

**Comment by cdeil** [comment]
I'm closing this issue now.

@jaromrax - Please have a look at my last comment, and if that doesn't help, post another message here and I'll re-open the issue to discuss further.
