### ISSUE TITLE
How to deal with is_above_max_edm=True?

### ISSUE THREAD

**Issue by Guang91** [iminuit/iminuit#195]
Hi,

I'm using iminuit for model fitting. However, sometimes iminuit fails to converge due to is_above_max_edm=True. So, What's the cause? Any suggestions about debugging?

Sorry, my likelihood function is very complex, so I cannot simply upload a .py code.

Thanks,
Guang

**Comment by Guang91** [comment]
I've found the issue: my likelihood has some discontinuity, resulting in infinite derivative sometimes. This is fixed now. Thanks.

Guang

**Comment by cdeil** [comment]
@Guang91 - I'm glad you figured out the problem and found a solution!

Fitting with MINUIT and in general is very complex, and most scientists (including me) don't really understand the underlying numerical procedure well.

So clearly it would be nice if the iminuit docs contained examples and advice on common things that can to wrong (like likelihood discontinuity in your case) and how they will manifest in a response by MINUIT, and then advice how to debug and fix it (I guess fix likelihood function implementation in your case).

I don't have time, but @Guang91 or anyone else watching the iminuit tracker -- just know that pull requests in that direction to the iminuit docs would be very welcome any time.

**Comment by Guang91** [comment]
@cdeil Sure, I'm happy to start a pull request. But I'm also quite busy, so it might take some time....
