### ISSUE TITLE
iminuit algorithm?

### ISSUE THREAD

**Issue by Guang91** [iminuit/iminuit#196]
Hi,

I find there are three minimization algorithms in the original minuit paper (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.158.9157&rep=rep1&type=pdf)

However, it seems iminuit only has one algorithm (i.e., migrad). 
Does that mean iminuit is a simplified version of minuit?

Thanks,
Guang

**Comment by alexpearce** [comment]
Yes, that's right. The `SCAN` (or `SEEK`) and `SIMPLEX` algorithms are not currently exposed.

Issues #101 and #104 deal with the same issue.
