### ISSUE TITLE
pixellation issues in contour plots in highly covariant variables

### ISSUE THREAD

**Issue by johnsmorgan** [iminuit/iminuit#198]
I am using iminuit to do some fitting with very strong covariance between variables and I'm getting a lot of contour plots that look like this by default:
![image](https://user-images.githubusercontent.com/3793500/27530162-0a475536-5a8a-11e7-9a97-e22e6dee28cb.png)

This should show a thin ellipse. It doesn't due to the pixellation of the underlying data
![image](https://user-images.githubusercontent.com/3793500/27531702-357f5004-5a90-11e7-800b-85d6b7ecd8f3.png)

If I zoom in with nbin=40 and bound=0.5, the true covariance is clearly well-behaved.
![image](https://user-images.githubusercontent.com/3793500/27531488-5e2c4e68-5a8f-11e7-8e28-3a627142e217.png)
 
I would suggest having an odd number as the default for 'bins' as this at least ensures a central peak. 
![image](https://user-images.githubusercontent.com/3793500/27531057-ca5721be-5a8d-11e7-813d-f8b88fd119f4.png)

Having the option to add the raster image (via imshow) under the contours might also be useful option, and perhaps should be considered as the default.

**Comment by cdeil** [comment]
@johnsmorgan - Apologies for not responding here.

I'm not sure what exactly you mean here or how to devise a simple test case.

Are you just suggesting to change the default for `bins=30` in
http://iminuit.readthedocs.io/en/latest/api.html#iminuit.Minuit.draw_mnprofile
to e.g. `bins=31`? Would that help in your case?

**Comment by HDembinski** [comment]
I think I understand the issue. Using uneven bin number may improve the situation but does not solve the underlying problem. The way how the contour plot is made is wrong. I need to have a closer look into draw_mnprofile to fix this properly. The MINOS algorithm is able to draw exact contours. We should not use these brittle approximations.

**Comment by cdeil** [comment]
@HDembinski - OK.

But there's a ton of methods to contour and parameters.

As always, my suggestion would be to mainly improve the docs, and refer them to scikit-image and MPL contouring, advertise these plot methods in iminuit only as quick-look.

**Comment by HDembinski** [comment]
And as always, I don't want to be responsible for a software that gives such dangerously wrong results.

**Comment by HDembinski** [comment]
Addressed in PR #255

**Comment by cdeil** [comment]
Should be fixed by #255 from @HDembinski .
