### ISSUE TITLE
Replace shields.io badges

### ISSUE THREAD

**Issue by HDembinski** [iminuit/iminuit#209]
In `README.rst`, we use `shields.io` show some badges. Especially the Travis and Appveyor badges are pretty important, showing that the master branch is working properly. I want to replace the shields.io links with the original badge links, at least the ones for Travis and Appveyor.

The `shields.io` image links are very often broken when I look at them on Github. They are slow to load and often not show up at all. I checked just now and several show the "broken image link" symbol. I never had such issues in other projects, where I used the original badge code provided by Travis and Appveyor in Markdown files. Another bad thing about `shields.io` is that the Appveyor badge looks identical to the Travis badge. It is good to visually identify which one is which.

What was the original reason to use `shields.io`?

**Comment by cdeil** [comment]
Probably a copy & paste mistake by me. Can you please update the badges?

**Comment by HDembinski** [comment]
Fixed in PR #214
