### ISSUE TITLE
change current parameter state

### ISSUE THREAD

**Issue by HDembinski** [iminuit/iminuit#230]
There seems to be no way to change the current parameter state in an existing Minuit instance.

Changes made to `m.fitarg[name]` or `m.values[name]` are ignored. This is extremely confusing, because these values should not be settable, if they are read-only.

Changes in `m.fitarg`, `m.values`, and `m.errors` should actually update the internal state of Minuit.

Related to #163 #105

**Comment by cdeil** [comment]
@HDembinski - I'm going through the issues with no milestone, setting something.

Is this a v1.3 item? If no, please move to a later milestone.
