### ISSUE TITLE
Installation fails without cython

### ISSUE THREAD

**Issue by raymondEhlers** [iminuit/iminuit#234]
Thanks for your hard work on this excellent package! Attempting to install the master without `cython` fails with the following output:

```
(testEnv) user@MBP ~/code/test/minuitTests/iminuit $ pip install git+git://github.com/iminuit/iminuit.git#egg=iminuit
Obtaining file:///Users/user/code/test/minuitTests/iminuit
Requirement already satisfied: setuptools in /Users/user/code/test/minuitTests/testEnv/lib/python3.6/site-packages (from iminuit==1.2) (39.0.1)
Requirement already satisfied: numpy in /Users/user/code/test/minuitTests/testEnv/lib/python3.6/site-packages (from iminuit==1.2) (1.14.5)
Installing collected packages: iminuit
  Running setup.py develop for iminuit
    Complete output from command /Users/user/code/test/minuitTests/testEnv/bin/python3 -c "import setuptools, tokenize;__file__='/Users/user/code/test/minuitTests/iminuit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    Cython is not available ... using pre-generated C file.
    running develop
    running egg_info
    writing iminuit.egg-info/PKG-INFO
    writing dependency_links to iminuit.egg-info/dependency_links.txt
    writing requirements to iminuit.egg-info/requires.txt
    writing top-level names to iminuit.egg-info/top_level.txt
    reading manifest file 'iminuit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.cpp' under directory 'iminuit'
    writing manifest file 'iminuit.egg-info/SOURCES.txt'
    running build_ext
    building 'iminuit._libiminuit' extension
    creating build
    creating build/temp.macosx-10.13-x86_64-3.6
    creating build/temp.macosx-10.13-x86_64-3.6/Users
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test/minuitTests
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test/minuitTests/iminuit
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test/minuitTests/iminuit/iminuit
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test/minuitTests/iminuit/Minuit
    creating build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test/minuitTests/iminuit/Minuit/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/user/code/test/minuitTests/iminuit/Minuit/inc -I/Users/user/code/test/minuitTests/testEnv/lib/python3.6/site-packages/numpy/core/include -I/Users/user/code/test/minuitTests/testEnv/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c /Users/user/code/test/minuitTests/iminuit/iminuit/_libiminuit.c -o build/temp.macosx-10.13-x86_64-3.6/Users/user/code/test/minuitTests/iminuit/iminuit/_libiminuit.o -Wno-shorten-64-to-32 -Wno-parentheses -Wno-unused-variable -Wno-sign-compare -Wno-cpp
    clang: error: no such file or directory: '/Users/user/code/test/minuitTests/iminuit/iminuit/_libiminuit.c'
    clang: error: no input files
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/user/code/test/minuitTests/testEnv/bin/python3 -c "import setuptools, tokenize;__file__='/Users/user/code/test/minuitTests/iminuit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/user/code/test/minuitTests/iminuit/
```

As a workaround, it installs correctly if I install `cython` first, which is fine (I had intended to install it anyway, but I forgot to do so in a new `virtualenv`), but it wasn't obvious to me that doing so would resolve it

**Comment by cdeil** [comment]
I'm not sure if there is a good way to write `setup.py` so that `cython` is a dependency for an iminuit dev version install, but not for normal install.

Maybe we should just improve the docs here to give the correct commands to install the dev version, i.e. a `pip install Cython` first?
http://iminuit.readthedocs.io/en/latest/installation.html#development-version

**Comment by HDembinski** [comment]
I don't think that documenting is the right solution, we should try to fix this in the setup.py

Installation must work, otherwise we loose new users. There are so many people which just try a pip install and if it does not work, they ignore the package. I am like that. Why should I read the docs in that case? I am not yet invested in this package and if it does not even install, it is obviously not worth my time.

**Comment by HDembinski** [comment]
Plus, setup.py is written in a way that installation without Cython should be possible. If it does not work, this is a bug. Apparently, this case is not unit tested on Travis. So we should fix this and test this setup on Travis.

**Comment by cdeil** [comment]
@HDembinski - If there is a good solution, OK.

But I don't think this is a big problem. Users should not have to install a dev version or need Cython. We should just make a new release.

I'm not sure there is an easy fix, my guess would be that other package like Numpy, Scipy, scikit-image, scikit-learn that are used by millions fail in the same way if you try to install the dev version without having Cython installed before.

**Comment by HDembinski** [comment]
@cdeil Ok, I wasn't sure what you meant by "dev version", but you say that someone who is installing from github is not your average user. Ok, true. Nevertheless, maybe it is simple to fix so I will give it a try.

**Comment by raymondEhlers** [comment]
Hi @cdeil , @HDembinski ,

Thanks for your quick responses and actions! As one additional note, I was installing the package from the repo instead of PyPi because the available tag is from a few years ago. I don't remember the particular reason that I was looking to update, but I seem to recall that I noticed some sort of problem with iminuit (perhaps python 3 related - in any case, fixed in the master) when installing probfit from GitHub (again, because the tag there is old and doesn't work properly with python 3). So from my perspective, a new release would be extremely helpful!

**Comment by raymondEhlers** [comment]
Hi @HDembinski,

Excellent - I'm looking forward to it!

**Comment by cdeil** [comment]
We improved the setup.py and docs today: #236 #238

Basically before installing the dev version you should always install cython and numpy first.

We should really release a new version in the next days, users shouldn't have to bother with dev version.

Closing this now, but of course, new PRs to improve docs or even setup.py or issue reports are welcome any time.
