### ISSUE TITLE
Add test for is_fixed

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#239]
Cython coverage (#158) shows that this function isn't covered by a test:
https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L814-L822

Actually the `%s` in the `RunTimeError` message that isn't filled is a bug, no?

@HDembinski - You or me?

**Comment by HDembinski** [comment]
I will add a test and fix the bug.

**Comment by HDembinski** [comment]
Is addressed in PR, closing...
