### ISSUE TITLE
Add test for fix option in from_array_func

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#241]
Cython coverage (#158) shows that this function isn't covered by a test:
https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L484

@HDembinski - Worth adding a test?
(if no, please add `#pragma: nocover`)

**Comment by HDembinski** [comment]
Is addressed in PR, closing...
