### ISSUE TITLE
Add test for hesse for function with gradient

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#242]
Cython coverage (#158) shows that hesse for a function with gradient isn't covered by a test:

https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L619-L624

@HDembinski - Can you please add a test for this?

**Comment by HDembinski** [comment]
Is addressed in PR, closing...
