### ISSUE TITLE
Add test for latex_param

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#243]
Cython coverage (#158) shows that this isn't covered by a test:
https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L844-L847

This as well:
https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L877-L880

I'll have a look and add something.

**Comment by HDembinski** [comment]
Once you write tests for this, also #244 will be covered.

**Comment by cdeil** [comment]
Isn't #244 core functionality of iminuit and this LaTeX table is a bit of sugar?
The core functionality should be tested separately.

**Comment by HDembinski** [comment]
No this is not core functionality. Only to report to users. Nevertheless, I am with you on testability, but we get that for free if you merge `_prepare_initial_param` with `get_initital_param_state`.

**Comment by cdeil** [comment]
Done by @HDembinski  in #163 .
