### ISSUE TITLE
Rewrite _prepare_initial_param in a better way

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#244]
Cython coverage (#158) shows that several lines in _prepare_initial_param are not covered by a test:

https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L849

Check this out:
![screen shot 2018-06-20 at 19 45 32](https://user-images.githubusercontent.com/852409/41675388-e10bded6-74c2-11e8-820a-bc0039b6fbe7.png)

Note the commas at the end of some lines, but not others, and the if statements, all in the `Struct()` function call. This is very hard to read / understand and error-prone code. And apparently several lines are never executed and are thus completely untested, if the coverage report is to be trusted for this complex case.

@HDembinski - Can you please have a look and make it better? Probably move all computations before the `Struct()` call? Is your #230 related or separate?

**Comment by HDembinski** [comment]
This is just not properly indented. The original author used the `result_a if cond else result_b` syntax. The `if`s just need to be indented to make this more clear.

**Comment by HDembinski** [comment]
If you look where the code is actually called, it is just used to print the initial parameters. This is not related to #230.

In fact this whole function could be removed if the Minuit was better designed. I will not touch this, since my time is better spend elsewhere.
