### ISSUE TITLE
Release iminuit v1.3

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#246]
@HDembinski and I plan to release iminuit v1.3 on June 27, 2018, so I've set the date for the milestone:
https://github.com/iminuit/iminuit/milestone/4

@piti118 @alexpearce or anyone - if you have anything that should be done for v1.3, or even have time to tackle some of the issues, please let us know.

We can use this issue to discuss the release overall, and to keep track of the steps and issues during the release. I find that such a record is useful, and also sometimes helps for the next release to see what was done in the last release.

**Comment by cdeil** [comment]
Just for the record: there was a lot of confusion concerning the v1.2, v2.0 and v2.1 milestones, because I had made the v2.0 milestone but then that release was called v1.2 two years ago.
I removed the v2.1 milestone for now (no work on this done yet), and reset the milestone for v1.2 and v2.0 appropriately. Everything should be correctly set now.

**Comment by cdeil** [comment]
Most issues / tasks have been addressed, only very few left: https://github.com/iminuit/iminuit/milestone/4
Review or help there is welcome.

@HDembinski and I plan to cut the v1.3 release tomorrow (July 5).

**Comment by cdeil** [comment]
@HDembinski - I think `master` is ready for the v1.3 release now, if you want to go ahead.

If you have time to look at #272 or #270 and see if improving / fixing those is possible with little work, that could still go in v1.3, but I think it's also OK to do those later for v1.4.

There's so many changes in v1.3 to the build and internals that I suspect we'll need a follow-up release relatively soon anyways, after some user testing / feedback.

**Comment by HDembinski** [comment]
Release 1.3 was tagged and uploaded to PyPI
https://pypi.org/project/iminuit/

**Comment by HDembinski** [comment]
@cdeil Same to you 😄
