### ISSUE TITLE
Add option to store parameter trace?

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#253]
Should we add an option in Minuit to store a trace with the parameters that were made in the function calls?

I think it could be useful, especially when the minimisation fails for debugging. Given that it's cheap and simple to store, it could even be on by default?

Note that e.g. samplers store this, although of course there it's the key result, whereas here it's mostly useful for debugging non-converging fits, or performance issues with a given function:
http://dfm.io/emcee/current/api/#emcee.EnsembleSampler.flatchain

One question is whether it should be per Minuit instance or per migrad etc function call, i.e. when to clear the trace.

I'm not sure if we should add this, especially because different users want to clear the trace at different times and we don't want a complex API for this. An alternative could be to give a docs example showing users how to store this themselves. This is done by @HDembinski in #252 , although the current example is non-optimal, because it contains an unused class-level `trace=[]`, then really using instance-level `trace` attribute below. IMO either instance-level, or global variables should be used, created directly before the Minuit creation or migrad / minos / ... call one wants to trace.

**Comment by HDembinski** [comment]
@cdeil I am against adding support for this in iminuit. Writing a wrapper to trace the calls is super trivial in Python.

>This is done by @HDembinski in #252 , although the current example is non-optimal, because it contains an unused class-level trace=[], then really using instance-level trace attribute below. IMO either instance-level, or global variables should be used, created directly before the Minuit creation or migrad / minos / ... call one wants to trace.

Why do you say the class-level trace is unused? Sure it is used.

```
class A:
    trace = []
    def __call__(self, x):
          self.trace.append(x)

assert A.trace == []
a = A()
a(1)
assert a.trace == [1]
assert A.trace == [1]
```
This is, in fact, a common bug for new Python users, because people think `A.trace` is instance-level.

**Comment by HDembinski** [comment]
Can we close this?

**Comment by cdeil** [comment]
Sure, let's close if you prefer. I think a docs example how to do this would be nice, but I don't have time to add it.
