### ISSUE TITLE
Fix tutorial/hard-core-tutorial.ipynb

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#257]
As mentioned in #245, the [tutorial/hard-core-tutorial.ipynb](https://github.com/iminuit/iminuit/blob/master/tutorial/hard-core-tutorial.ipynb) is currently broken, at least for me locally and on travis-ci with Python 3.

This is a reminder issue to fix it, and to uncomment this line to test it in CI:
https://github.com/iminuit/iminuit/blob/2095c30cb704d451a3a0cccc09463513140b82de/test_notebooks.py#L28-L31

Also, it's currently pretty slow, it only crashes after a minute or two. IMO to learn it's best to have tutorials that execute very fast (a few sec only), because one makes many mistakes and wants to hack on the code and play with parameters and execute many times.
So IMO the notebook should be changed to run faster, either by choosing faster examples or by running timeit with different options.

I don't have time this week. @HDembinski - if it's quick for you to reproduce and fix, please have a look. If not, please defer to the next milestone.

**Comment by HDembinski** [comment]
I am closing this. The tutorial failed for you, because you ran it on a computer with a clang compiler. As it is explicitly stated in the hardcore tutorial, the last section that uses openmp only works with gcc.
