### ISSUE TITLE
fix auto_frontend detection of ipython vs ipython notebook

### ISSUE THREAD

**Issue by HDembinski** [iminuit/iminuit#260]
See comment from @cdeil https://github.com/iminuit/iminuit/pull/256#discussion_r200041276

The current `auto_front()` code cannot distinguish between the ipython shell as a ipython notebook and loads the html frontend in both cases. We want the console frontend to load for ipython shell and html frontend for ipython (and jupyter) notebook.

It is currently not clear how to fix this, suggestions welcome!

**Comment by cdeil** [comment]
I just noticed that `print_fmin` and all the other print methods are completely broken, they give no output from `ipython`:
```
(gammapy-dev) hfm-1804a:gammapy deil$ ipython
Python 3.6.0 | packaged by conda-forge | (default, Feb 10 2017, 07:08:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from iminuit import Minuit
   ...: 
   ...: def f(x, y, z):
   ...:     return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2
   ...: 
   ...: m = Minuit(f)
   ...: 
   ...: m.migrad()  # run optimiser
   ...: print(m.values)  # {'x': 2,'y': 3,'z': 4}
   ...: 
   ...: m.hesse()   # run covariance estimator
   ...: print(m.errors)  # {'x': 1,'y': 1,'z': 1}
   ...: 
   ...: 
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: Parameter x does not have initial value. Assume 0.
  
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: Parameter x is floating but does not have initial step size. Assume 1.
  
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: Parameter y does not have initial value. Assume 0.
  
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: Parameter y is floating but does not have initial step size. Assume 1.
  
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: Parameter z does not have initial value. Assume 0.
  
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: Parameter z is floating but does not have initial step size. Assume 1.
  
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/ipython:6: InitialParamWarning: errordef is not given. Default to 1.
  
<ValueView of Minuit at 7fb33d9577c8>
  x: 2.0000000000047327
  y: 3.000000000007099
  z: 4.000000000009465

<ErrorView of Minuit at 7fb33d9577c8>
  x: 1.0000000000000402
  y: 0.9999999999999426
  z: 1.0000000000001645


In [2]: m.print_fmin()

In [3]: 
```

I haven't looked at ipython / Jupyter repr stuff in years, but there might be some way to do it better mentioend here:
https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

If it's not easily possible, we should probably change to do the safe thing and print out text by default, even at the cost of not so nice output in Jupyter?

**Comment by HDembinski** [comment]
We could try this from SO
```
def in_ipynb():
    try:
        cfg = get_ipython().config 
        if cfg['IPKernelApp']['parent_appname'] == 'ipython-notebook':
            return True
        else:
            return False
    except NameError:
        return False
```

**Comment by HDembinski** [comment]
I personally don't use Jupyter a lot, but I think the html output is nice. I spend some time for 1.3 to fix a few minor bugs. I noticed that I introduced other minor bugs to the console output. I will try to address these issues in PRs for the next version 1.3.3

**Comment by cdeil** [comment]
What we have now

https://github.com/iminuit/iminuit/blob/705bf9f05d8dd267497b30813034c5579f6120f0/iminuit/_libiminuit.pyx#L78-L89

is just plain wrong for the case of the ipython terminal, no?

It selects the HTMLFrontend, but should select the ConsoleFrontend.

```
$ ipython
Python 3.6.0 | packaged by conda-forge | (default, Feb 10 2017, 07:08:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: __IPYTHON__
Out[1]: True
```

Looking around, if I understand correctly, the only reliable way to is to use
https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display
i.e. to change everything to return objects that have a `__repr__` that is then shown in text output and a `_repr_html_` that will be called in Jupyter.

I'm not even sure if that's possible for us while keeping backward compat. I guess we'd have to return small wrapper / proxy objects with those added in?

I also don't know how to test the ipython / Jupyter behaviour. E.g. clearly we're missing a test that runs `minuit.print_fmin` in `ipython` terminal and checks that something is printed. So we didn't catch that it's broken there. I think it was already broken in 1.2, which I find really surprising that no-one noticed. I guess not many people are calling `print_fmin`.

So @HDembinski - this is a difficult one and I'm not helpful. Feel free to make any change you think best, if you have time to look into this issue.

**Comment by HDembinski** [comment]
Yes, the problem is with the auto_frontend detection. Like you say, using this rich-display is a crazy big change that does not fit with the structure that's already in iminuit. The easy fix is a better detection of the notebook kernel. Why don't you think we can use this `in_ipynb()` function?

**Comment by cdeil** [comment]
I just have no idea if that works reliably. Let’s put it in master and have a few people try it out this week?

**Comment by HDembinski** [comment]
@cdeil I added a fix that works on my machine and added some tests which check the new detection for the python shell and the ipython shell. I do not see a way to test it automatically in a Jupyter notebook.

**Comment by HDembinski** [comment]
In other words, I can test the negative cases, that `is_ipython_notebook()` returns false for a python and ipython shell, but I do not see a why to test the positive case, where it returns true.

**Comment by HDembinski** [comment]
Nevermind, I found a way to also test the notebook case

**Comment by HDembinski** [comment]
fixed in master now
