### ISSUE TITLE
Clarify when running hesse is needed / useful

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#264]
We should clarify when running `hesse` after `migrad` is needed / useful.

Users notice that `errors` are available after `migrad` and often don't run `hesse`.

Should the recommendation simply be to always run `hesse` if accessing `errors`?
Or are there cases where this is a waste of time, because `migrad` is already doing it at the end?

**Comment by HDembinski** [comment]
I did some numerical experiments. MINUIT by default uses strategy 1 (or 0 to 2). The error returned was always accurate in my simple trials, but those were quadratic functions where the HESSE matrix is the same everywhere. I suppose when you hand MINUIT a function to minimize, where the HESSE matrix depends on a lot on where you are in the parameter space, it could be necessary to call HESSE. However, MINUIT actually often calls HESSE on its own after it found the minimum. If that's the case, it is superfluous to call HESSE manually again.

When you change the strategy to 0, things change. Then you really need to call HESSE explicitly at the end of the minimization to get correct errors.

**Comment by HDembinski** [comment]
Will be addressed by issue #304
