### ISSUE TITLE
test_builtin_by_parsing_doc fail on Python 3.7

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#270]
Over in #267 I also added a `3.7-dev` build.

There's one fail: `test_builtin_by_parsing_doc`:
https://travis-ci.org/iminuit/iminuit/jobs/401188789#L1016

Putting this under the v1.4 milestone, IMO this should not delay the v1.3 release; this can be fixed in the coming weeks.

**Comment by cdeil** [comment]
Conda now creates Python 3.7 environments by default, so users are starting to use Python 3.7 now and we should fix that one fail.

I can reproduce it locally with
```
conda create -y -n iminuit-270 python=3.7 cython numpy scipy ipython matplotlib pytest
conda activate iminuit-270
pytest iminuit
```
or just with 
```
from math import ldexp
from iminuit.util import describe
describe(ldexp, True)
```

I think the signature was taken from the docstring in that case, in Python 3.6 I see:
```
>>> ldexp.__doc__
'ldexp(x, i)\n\nReturn x * (2**i).'
```
and in Python 3.7 I see:
```
>>> ldexp.__doc__
'Return x * (2**i).\n\nThis is essentially the inverse of frexp().'
```

My suggestion would be to just xfail this test for Python > 3.6, activate CI testing for 3.7 and move on. I could send a PR for this now.

I actually think there might be no way to get the signature, so probably there isn't really an alternative.
```
>>> import inspect
>>> inspect.signature(ldexp)
ValueError: no signature found for builtin <built-in function ldexp>
```

@HDembinski - OK?

**Comment by HDembinski** [comment]
Sounds good!

**Comment by cdeil** [comment]
Done in #291 .
