### ISSUE TITLE
travis CI dropped out

### ISSUE THREAD

**Issue by HDembinski** [iminuit/iminuit#275]
I am not seeing new travis builds since two days. The latest PRs went unchecked by travis. @cdeil this seemed to start after you committed the Travis patch. Could you have a look, please?

**Comment by HDembinski** [comment]
@cdeil I think your change of travis broke the script, see:
![screen shot 2018-07-16 at 14 11 09](https://user-images.githubusercontent.com/2631586/42757978-2f25a202-8902-11e8-937d-275a0655ed84.png)

**Comment by HDembinski** [comment]
I think this commit broke it: 4c01da2d636ba709e585a04f4328a099df833959

**Comment by cdeil** [comment]
Looks like there's a YAML parse error on `.travis.yml`. I'll have a look and try to fix now.

**Comment by cdeil** [comment]
I fixed the YAML syntax error in 8f0a135b8e507070f4da182b5e2194419e87ab0b and it's alive again:
https://travis-ci.org/iminuit/iminuit/builds/404424229

**Comment by HDembinski** [comment]
Cool, thanks!

**Comment by HDembinski** [comment]
is fixed
