### ISSUE TITLE
docs: make sections about initial step size and errordef

### ISSUE THREAD

**Issue by HDembinski** [iminuit/iminuit#282]
See https://github.com/gammapy/gammapy/issues/1531#issuecomment-405856533

Explain better how initial step size is used and what to set in an extra section. Also give errordef an extra section. There is not much else to write, but the sections help to find information about these topics quickly.

**Comment by cdeil** [comment]
What we've done in Gammapy it to introduce a Parameter and Parameters class where the parameter value is the product of a "factor" and a "scale":

https://github.com/gammapy/gammapy/blob/27d651f0f2d17efa657dbe5e6ec4567c07cca939/gammapy/utils/modeling.py#L118-L121

and then the likelihood and user see "value", but the optimiser / iminuit interface sees "factor"

We have an autoscale:

https://github.com/gammapy/gammapy/blob/27d651f0f2d17efa657dbe5e6ec4567c07cca939/gammapy/utils/modeling.py#L157-L183

and the translation from factor to value covariance matrix is here:

https://github.com/gammapy/gammapy/blob/27d651f0f2d17efa657dbe5e6ec4567c07cca939/gammapy/utils/modeling.py#L392-L399

A docs section in iminuit could mention both options: pass parameter error to get initial step sizes, or do the factor / scale split and let iminuit interact with the factors.

**Comment by HDembinski** [comment]
fixed in master

**Comment by cdeil** [comment]
@HDembinski - Thank you!
