### ISSUE TITLE
Automatic cythonize

### ISSUE THREAD

**Issue by piti118** [iminuit/iminuit#29]
...turns

``` python
def f(x,y,z) in to
    blah blah
```

in to this, at run time and compile it.

``` python
cdef double f(vector[double] v):
    cdef double x = v[0]
    cdef double y = v[1]
    cdef double z = v[2]
    blah blah
```

And use special PythonFCN that takes this function pointer that looks like this. This will get rid of all python function call.

**Comment by cdeil** [comment]
I'm closing this old issue because there's no specific action item for iminuit here.

Of course, more docs how to connect iminuit to Cython, pybind11, numba or tips and tricks that are useful to write models and cost functions would be welcome in the future.
