### ISSUE TITLE
Linker errors after pip install iminuit with conda

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#292]
@facero reported on Gammapy slack that he got a broken `iminuit` after `pip install -U iminuit` for the latest iminuit 1.3.2 with conda on macOS.

There's no concrete action item here, @HDembinski - we can close if you prefer.

I just wanted this on the record because it's not unlikely that other users might run into such issues.

And we could improve the CI setup with more builds that also use conda. E.g. travis-ci has an open TODO to add MacOS builds.

First the pip install seems to work:
```
(cta) 13:54-sapmcn177 gammapy/$  pip install -U iminuit
Collecting iminuit
  Downloading https://files.pythonhosted.org/packages/4b/74/7918cd792c873b4424c0a88df6ab77065e9c17c071f4f0e090eea57b285d/iminuit-1.3.2.tar.gz (473kB)
    100% |████████████████████████████████| 481kB 3.0MB/s
Requirement not upgraded as not directly required: setuptools in /Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg (from iminuit) (27.2.0)
Requirement not upgraded as not directly required: numpy in /Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages (from iminuit) (1.12.1)
Building wheels for collected packages: iminuit
  Running setup.py bdist_wheel for iminuit ... done
  Stored in directory: /Users/facero/Library/Caches/pip/wheels/9e/46/a2/03d797e62a744753754ab7f021ffd7b4c93d58c04da3904a31
Successfully built iminuit
Installing collected packages: iminuit
  Found existing installation: iminuit 1.2
    Uninstalling iminuit-1.2:
      Successfully uninstalled iminuit-1.2
Successfully installed iminuit-1.3.2
```

But then there was a dlopen / linker / symbol not found error on import:
```
(cta) 14:21-sapmcn177 gammapy/$  which python
/Users/facero/Documents/Work/Program/Anaconda/envs/cta/bin/python
(cta) 14:22-sapmcn177 gammapy/$  python -c 'import iminuit'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit/__init__.py", line 28, in <module>
    from ._libiminuit import Minuit
ImportError: dlopen(/Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so
```

At first I thought the issue is caused by a mix of import / linking between different iminuit installs, from the cta env and the base env. But looking at this I think the problem is that the dynamic linking happens against `/usr/local/Cellar/gcc@4.7/4.7.4_2/lib/gcc/x86_64-apple-darwin16.6.0/4.7.4/libgcc_s.1.dylib` which comes from HomeBrew:

```
(cta) 14:22-sapmcn177 gammapy/$  otool -L /Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so
/Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/local/Cellar/gcc@4.7/4.7.4_2/lib/gcc/x86_64-apple-darwin16.6.0/4.7.4/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
(cta) 15:19-sapmcn177 gammapy/$  find /Users/facero/Documents/Work/Program/Anaconda -name iminuit
/Users/facero/Documents/Work/Program/Anaconda/envs/cta/lib/python3.6/site-packages/iminuit
/Users/facero/Documents/Work/Program/Anaconda/lib/python3.6/site-packages/iminuit
/Users/facero/Documents/Work/Program/Anaconda/pkgs/iminuit-1.2-py36_0/lib/python3.6/site-packages/iminuit
```

I'm not sure why this is happening, i.e. if it's a build-time or import-time config issue.

For me it looks like this on MacOS, even though I also have Homebrew installed:
```
(gammapy-dev) hfm-1804a:gammapy deil$ otool -L /Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so 
/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so:
    @rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

The problem might be that @facero is using an old coda install, and one solution would be to wipe that and re-install the latest Anaconda, but of course that's one to a few hours of work. So for now he did:
```
pip uninstall iminuit
conda install -f iminuit -c conda-forge
```
and will wait for conda packages for v1.3 to arrive.

The problem also could be other environment settings like `LD_PATH` etc that affect dynamic linking.

His conda environment info is here:
https://gist.github.com/cdeil/67ade856da28a063b9a3f196b7e39866

**Comment by HDembinski** [comment]
Hi, it is generally not a good idea to have several compilers installed. I think this problem would not appear if @facero used apple clang instead of gcc installed with homebrew.
Next, let's demangle the missing reference:
```
$ c++filt __ZNSs4_Rep20_S_empty_rep_storageE
std::string::_Rep::_S_empty_rep_storage
```
This is some `std::string` internal from the c++ std library. Since @facero has gcc installed in addition to Apple clang, there are probably two versions of the c++ std library present, one from Apple clang and one from gcc. Apparently, pip uses one in the build but then tries to link to the other at run-time.

**Comment by HDembinski** [comment]
A little googling shows that the missing reference is from the gcc implementation of `std::string`.

**Comment by cdeil** [comment]
The idea with Anaconda since one or two years is that they ship the compiler and (I think) C++ std lib and configure the env so that it should get picked up 
https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

For me that is what happens:
```
(gammapy-dev) hfm-1804a:gammapy deil$ which clang
/Users/deil/software/anaconda3/envs/gammapy-dev/bin/clang
(gammapy-dev) hfm-1804a:gammapy deil$ which gcc
/usr/bin/gcc
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
and
```
(gammapy-dev) hfm-1804a:gammapy deil$ otool -L /Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so 
/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-darwin.so:
    @rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```
I don't have anything set here:
```
env | grep LIBRARY_PATH
```

This also has useful infos: https://conda.io/docs/user-guide/tasks/build-packages/use-shared-libraries.html#shared-libraries-in-macos-and-linux 

@facero - can you please past the output of these commands when you have the cta env active?
```
env | grep LIBRARY_PATH
which clang
which gcc
clang --version
gcc --version
```

Overall I still don't fully understand what is happening and I'm not sure if tracking this down further will help. I think both a complete re-install of current Anaconda by @facero would resolve the problem, and also iminuit conda-forge packages would resolve it.

**Comment by HDembinski** [comment]
@cdeil In your case, it uses `@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)`
In my case (also OSX, no Anaconda), I get
`/usr/lib/libc++.1.dylib`

**Comment by HDembinski** [comment]
The website you linked to has good advice. Perhaps the solution is to unset *LIBRARY_PATH

**Comment by cdeil** [comment]
@HDembinski - Do you know other widely used C++ / Python projects that are distributed via PyPI / pip? Are they doing something special in setup.py, like using `rpath` os macOS?

**Comment by cdeil** [comment]
I found https://matthew-brett.github.io/docosx/mac_runtime_link.html#rpath with nice example, but it doesn't mention how to package C++ / Python via setup.py .

**Comment by facero** [comment]
@cdeil here is the output of my env and clang and gcc versions:

```
(cta) 10:28-sapmcn177 ~/$  env | grep LIBRARY_PATH
(cta) 10:28-sapmcn177 ~/$  which clang
/usr/bin/clang
(cta) 10:28-sapmcn177 ~/$  which gcc
/usr/local/bin/gcc
(cta) 10:28-sapmcn177 ~/$  clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(cta) 10:28-sapmcn177 ~/$  gcc --version
gcc (Homebrew GCC 4.7.4_2) 4.7.4
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cdeil** [comment]
So I think what happened is this: you have an older Anaconda that doesn't ship with a C++ compiler. The iminuit build picked up `/usr/local/bin/gcc` which is the one from Homebrew. The C++ std lib `/usr/local/Cellar/gcc@4.7/4.7.4_2/lib/gcc/x86_64-apple-darwin16.6.0/4.7.4/libgcc_s.1.dylib` that is picked up corresponds to that C++ compiler from Homebrew. It is incompatible with the Anaconda python.

@HDembinski - Why does the error happen only later at iminuit import time, but not at build time? Is it because `setup.py` only executes compiler commands, but the resulting shared lib is never imported at build time?

Again: I don't know if we can do anything here, besides maybe adding a note at the end of https://iminuit.readthedocs.io/en/latest/install.html mentioning the issue, and suggesting to update to a recent version of Anaconda if users get such a linker error.

@HDembinski - thoughs?

**Comment by HDembinski** [comment]
I think this a special problem on OSX. You have two gcc binaries on your system, the homebrew one and the fake one installed by Apple. Try `/usr/bin/gcc --version` and you will see that this is actually Apple clang. Somehow, setuptools mixes those up. Which is no suprise, because setuptools is a crappy build system.

**Comment by HDembinski** [comment]
One more reason to provide conda packages, I guess ¯\_(ツ)_/¯

**Comment by HDembinski** [comment]
So we have conda packages now. Can we close this?

**Comment by cdeil** [comment]
Yes, let's close.

If someone gets these linker issues in the future: you could try this to try to get pip to use the compiler from conda:
```
pip uninstall iminuit
CC=$CONDA_PREFIX/bin/gcc pip --no-cache-dir install iminuit
```
