### ISSUE TITLE
Add long double precision computations

### ISSUE THREAD

**Issue by piti118** [iminuit/iminuit#62]
port it to long double instead of double for better precision

iminuit/probfit#13

**Comment by cdeil** [comment]
@piti118 I don't know what needs to be done here. Can this issue be closed? or moved to the future or 1.3 milestone, i.e. not be adressed in the upcoming 1.2 release?

**Comment by piti118** [comment]
Make it a long term. We need to change a bunch of Minuit internal working for extra precision.

**Comment by aarchiba** [comment]
For people awaiting a solution to this (like me), there is a hack that probably will help: I wrote a wrapper that transforms the input parameters by subtracting an initial guess and dividing by an initial uncertainty guess. Then what's left fits into double precision (for me): the error ellipse is fine in double-land, it's just that it's a small error in the fourteenth decimal place of the original quantity.

**Comment by cdeil** [comment]
OK, closing.

@piti118 or @aarchiba - of course, if you have a suggestion to change something in iminuit, please re-open. Or if you have time to write a section or page in the docs with an example and some explanations how to do this scaling to achieve high precision with doubles, please send a pull request any time.
