### ISSUE TITLE
Replace pointer with auto ptr to get rid of memleak when throwing exception.

### ISSUE THREAD

**Issue by piti118** [iminuit/iminuit#80]
Just note here in case I forgot.

**Comment by cdeil** [comment]
@piti118 I don't know what needs to be done here. Can this issue be closed? or moved to the future or 1.3 milestone, i.e. not be adressed in the upcoming 1.2 release?

**Comment by piti118** [comment]
Move it to super long term. A lot needs to be done for this one.

**Comment by cdeil** [comment]
@HDembinski - Close? Or is there still an issue / possible memory leak with exception-handling?

**Comment by HDembinski** [comment]
I don't know, we don't have a test for memory leaks. Since I don't know what the original issue was, I cannot say whether it is still there. We should close this and reopen if we find serious issues with memory leaking.
