### ISSUE TITLE
Make Minuit.matrix and Minuit.print_matrix consistent

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#86]
At the moment Minuit.matrix() returns the covariance matrix and Minuit.print_matrix() prints the correlation matrix.
Can we make both them consistent and have the possibility to get and print both covariance and correlation matrix?
I think the best solution might actually be being very explicit here to avoid any confusion:

``` python
Minuit.covariance_matrix # property or method
Minuit.correlation_matrix # property or method
Minuit.print_covariance_matrix() # pretty-print
Minuit.print_correlation_matrix() # pretty-print
```

@piti118 What do you think?

**Comment by cdeil** [comment]
@piti118 At https://github.com/iminuit/iminuit/issues/86#issuecomment-17895524 you said it might be OK to break pyminuit compatibility to clean this up two years ago, but then I didn't make the change. Now in https://github.com/iminuit/iminuit/issues/153#issuecomment-126934620 you said it's better not to break compatibility.

What's your decision on this?
(I'm +1 to break compatibility.)

The two options are:
- Implement these improvements / cleanups now and break compatibility a little, call the next release 2.0.
- Keep compatibility for now and label this issue 2.0 which might happen at some point in the future.

**Comment by piti118** [comment]
Hahahahahaha. I disagree with my younger self.

If this function ever got in the way of making change, then we will remove it. But right now, it doesn't get in the way of anything. So we could just mark it deprecated and keep it as is.

**Comment by piti118** [comment]
Oh, it does get in the way..... so let's get rid of it.

**Comment by cdeil** [comment]
>  I disagree with my younger self.

It's normal to get more conservative as time goes by. :smile:

**Comment by HDembinski** [comment]
I think we can change print_matrix() to show the covariance matrix without breaking any user code. Then it would be consistent with matrix(). This seems like the simplest solution. Any objections?

**Comment by cdeil** [comment]
OK to change the print if this gives more consistency.

**Comment by HDembinski** [comment]
I gave this more thought: maybe we should live with the inconsistency and keep things the way they are. When you do "print_matrix()", you most likely want to see the correlation. The correlation is easy to mentally process, the covariance matrix is not easy to understand. The covariance matrix is useful when you do further calculations (error propagation), you don't want to print in an interactive session.

**Comment by cdeil** [comment]
ok
